### ISSUE TITLE
Configuration concept for discussion

### ISSUE THREAD

**Issue by nicksdlc** [nicksdlc/macaw#8]
This concept is out to show how the config file should look eventually and which features it should provide.

For concept HTTP connector was used

```
ConnectThrough: HTTP
HTTP:
  Serve:              # This is where we will host in case macaw works as a receiver
    Host: localhost
    Port: 1234
    Secured: false    # Big question mark here
  Remote:             # This is where we will send requests in case macaw works as sender
    Host: localhost
    Port: 4321
    Secured: false # Big question mark here
Mode: receiver
Response:
  # Build: for request with field("requestID") equals(2) respond with file("response_failed.json")
  # Build: for request like file("request.json") on endpoint("/evaluate") respond with file("response_short.json")
  # Build: for request on endpoint("/health") respond with content("{"status":"ok"}")
  Request:
    To: "/evaluate"
    Field: 
      Name: "requestID"
      Value: 2
  File: ./response_short_http.json
  Amount: 1
Request:
  # Build: send request to endpoint("/application/events") with body from file("request.json")
  File: ./request.json
  Destination: "/application/events"
  Delay: 0
  Amount: 1
```
The section Build in Request and Response is a big plan for the future to build kind of a language that will allow to build request and response in a more elegant fashion. 
For starter - yaml will be used to make request and responses more configurable.
